// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hero-variants/CardGrid.tsx": () => import("../components/mockups/hero-variants/CardGrid.tsx"),
  "./components/mockups/hero-variants/DarkSplit.tsx": () => import("../components/mockups/hero-variants/DarkSplit.tsx"),
  "./components/mockups/hero-variants/FloatCards.tsx": () => import("../components/mockups/hero-variants/FloatCards.tsx"),
  "./components/mockups/hero-variants/GlassOverlay.tsx": () => import("../components/mockups/hero-variants/GlassOverlay.tsx")
};
